/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Utilisation.Display;

import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import javax.swing.AbstractAction;
import javax.swing.ActionMap;
import javax.swing.InputMap;
import javax.swing.JComponent;
import javax.swing.KeyStroke;

/**
 *
 * @author GREGO
 */
public class DialogConfirmationCreationAbonne extends javax.swing.JDialog {

    /**
     * A return status code - returned if Cancel button has been pressed
     */
    public static final int RET_CANCEL = 0;
    /**
     * A return status code - returned if OK button has been pressed
     */
    public static final int RET_OK = 1;

    /**
     * Creates new form DialogConfirmationCreationAbonne
     */
    public DialogConfirmationCreationAbonne(java.awt.Frame parent, boolean modal, 
        String lg,
        String mp,
        String nom,
        String prenom,
        String adresse,
        String email,
        String telephone) {
        
    
        super(parent, modal);
        initComponents();
        
        lblLgOutput1.setText(lg);
        lblMpOutput.setText(mp);
        lblNomOutput.setText(nom);
        lblPrenomOutput.setText(prenom);
        lblAdresseOutput.setText(adresse);
        lblEmailOutput.setText(email);
        lblTelephoneOutput.setText(telephone);
        

        // Close the dialog when Esc is pressed
        String cancelName = "cancel";
        InputMap inputMap = getRootPane().getInputMap(JComponent.WHEN_ANCESTOR_OF_FOCUSED_COMPONENT);
        inputMap.put(KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0), cancelName);
        ActionMap actionMap = getRootPane().getActionMap();
        actionMap.put(cancelName, new AbstractAction() {
            public void actionPerformed(ActionEvent e) {
                doClose(RET_CANCEL);
            }
        });
    }

    /**
     * @return the return status of this dialog - one of RET_OK or RET_CANCEL
     */
    public int getReturnStatus() {
        return returnStatus;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        okButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        lblConfirmation = new javax.swing.JLabel();
        jLabel_lgInput = new javax.swing.JLabel();
        jLabel_mpInput = new javax.swing.JLabel();
        jLabel_nomInput1 = new javax.swing.JLabel();
        jLabel_prenomInput = new javax.swing.JLabel();
        jLabel_adresseInput = new javax.swing.JLabel();
        jLabel_mailInput = new javax.swing.JLabel();
        jLabel_mailInput1 = new javax.swing.JLabel();
        lblNomOutput = new javax.swing.JLabel();
        lblLgOutput1 = new javax.swing.JLabel();
        lblMpOutput = new javax.swing.JLabel();
        lblAdresseOutput = new javax.swing.JLabel();
        lblPrenomOutput = new javax.swing.JLabel();
        lblEmailOutput = new javax.swing.JLabel();
        lblTelephoneOutput = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        okButton.setText("OK");
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        lblConfirmation.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblConfirmation.setText("Confirmer la création de l'abonné");

        jLabel_lgInput.setText("Login");

        jLabel_mpInput.setText("Mot de passe");

        jLabel_nomInput1.setText("Nom");

        jLabel_prenomInput.setText("Prénom");

        jLabel_adresseInput.setText("Adresse");

        jLabel_mailInput.setText("Courriel");

        jLabel_mailInput1.setText("Téléphone");

        lblNomOutput.setText("                                             ");

        lblLgOutput1.setText("                                             ");

        lblMpOutput.setText("                                             ");

        lblAdresseOutput.setText("                                             ");

        lblPrenomOutput.setText("                                             ");

        lblEmailOutput.setText("                                             ");

        lblTelephoneOutput.setText("                                             ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblConfirmation)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(okButton, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(38, 38, 38)
                                .addComponent(cancelButton))
                            .addComponent(lblLgOutput1, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_mailInput1)
                            .addComponent(jLabel_mailInput)
                            .addComponent(jLabel_adresseInput)
                            .addComponent(jLabel_prenomInput)
                            .addComponent(jLabel_nomInput1)
                            .addComponent(jLabel_lgInput)
                            .addComponent(jLabel_mpInput)
                            .addComponent(lblMpOutput, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNomOutput, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPrenomOutput, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblAdresseOutput, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblEmailOutput, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTelephoneOutput, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(76, 76, 76)))
                .addContainerGap(84, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {cancelButton, okButton});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblConfirmation)
                .addGap(31, 31, 31)
                .addComponent(jLabel_lgInput)
                .addGap(1, 1, 1)
                .addComponent(lblLgOutput1)
                .addGap(18, 18, 18)
                .addComponent(jLabel_mpInput)
                .addGap(2, 2, 2)
                .addComponent(lblMpOutput)
                .addGap(18, 18, 18)
                .addComponent(jLabel_nomInput1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblNomOutput)
                .addGap(20, 20, 20)
                .addComponent(jLabel_prenomInput)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblPrenomOutput)
                .addGap(14, 14, 14)
                .addComponent(jLabel_adresseInput)
                .addGap(2, 2, 2)
                .addComponent(lblAdresseOutput)
                .addGap(18, 18, 18)
                .addComponent(jLabel_mailInput)
                .addGap(4, 4, 4)
                .addComponent(lblEmailOutput)
                .addGap(18, 18, 18)
                .addComponent(jLabel_mailInput1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTelephoneOutput)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelButton)
                    .addComponent(okButton))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        getRootPane().setDefaultButton(okButton);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        doClose(RET_OK);
    }//GEN-LAST:event_okButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        doClose(RET_CANCEL);
    }//GEN-LAST:event_cancelButtonActionPerformed

    /**
     * Closes the dialog
     */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        doClose(RET_CANCEL);
    }//GEN-LAST:event_closeDialog
    
    private void doClose(int retStatus) {
        returnStatus = retStatus;
        setVisible(false);
        dispose();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DialogConfirmationCreationAbonne.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DialogConfirmationCreationAbonne.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DialogConfirmationCreationAbonne.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DialogConfirmationCreationAbonne.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                /*DialogConfirmationCreationAbonne dialog = new DialogConfirmationCreationAbonne(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
                */
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JLabel jLabel_adresseInput;
    private javax.swing.JLabel jLabel_lgInput;
    private javax.swing.JLabel jLabel_mailInput;
    private javax.swing.JLabel jLabel_mailInput1;
    private javax.swing.JLabel jLabel_mpInput;
    private javax.swing.JLabel jLabel_nomInput1;
    private javax.swing.JLabel jLabel_prenomInput;
    private javax.swing.JLabel lblAdresseOutput;
    private javax.swing.JLabel lblConfirmation;
    private javax.swing.JLabel lblEmailOutput;
    private javax.swing.JLabel lblLgOutput1;
    private javax.swing.JLabel lblMpOutput;
    private javax.swing.JLabel lblNomOutput;
    private javax.swing.JLabel lblPrenomOutput;
    private javax.swing.JLabel lblTelephoneOutput;
    private javax.swing.JButton okButton;
    // End of variables declaration//GEN-END:variables

    private int returnStatus = RET_CANCEL;
}
