/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Utilisation.Display;

import javax.swing.JFrame;
import Utilisation.*;
import Source.*;
import java.util.ArrayList;
import java.util.Date;


/**
 *
 * @author GREGO
 */
public class FMenuCreationCompte extends javax.swing.JFrame {
    private GestionAbonne ga;
    /**
     * Creates new form FMenuCreationCompte
     */
    public FMenuCreationCompte(GestionAbonne g) {
        initComponents();
        ga = g;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Bouton_Close = new javax.swing.JButton();
        jTextField_mp_input = new javax.swing.JTextField();
        jTextField_lg_input1 = new javax.swing.JTextField();
        jTextField_adresseInput = new javax.swing.JTextField();
        jTextField_prenomInput = new javax.swing.JTextField();
        jTextField_telephoneInput = new javax.swing.JTextField();
        jTextField_nomInput = new javax.swing.JTextField();
        jTextField_mailInput = new javax.swing.JTextField();
        jLabel_lgInput = new javax.swing.JLabel();
        jLabel_mpInput = new javax.swing.JLabel();
        jLabel_prenomInput = new javax.swing.JLabel();
        jLabel_nomInput1 = new javax.swing.JLabel();
        jLabel_adresseInput = new javax.swing.JLabel();
        jLabel_mailInput = new javax.swing.JLabel();
        jLabel_mailInput1 = new javax.swing.JLabel();
        jButton_CreerAbonne = new javax.swing.JButton();
        BoutonRetour = new javax.swing.JButton();
        lgErreurOutput = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        Bouton_Close.setText("Fermer");
        Bouton_Close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Bouton_CloseMouseClicked(evt);
            }
        });

        jLabel_lgInput.setText("Login");

        jLabel_mpInput.setText("Mot de passe");

        jLabel_prenomInput.setText("Prénom");

        jLabel_nomInput1.setText("Nom");

        jLabel_adresseInput.setText("Adresse");

        jLabel_mailInput.setText("Courriel");

        jLabel_mailInput1.setText("Téléphone");

        jButton_CreerAbonne.setText("S'inscrire");
        jButton_CreerAbonne.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_CreerAbonneMouseClicked(evt);
            }
        });

        BoutonRetour.setText("Retour");
        BoutonRetour.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BoutonRetourMouseClicked(evt);
            }
        });

        lgErreurOutput.setFont(new java.awt.Font("DialogInput", 2, 14)); // NOI18N
        lgErreurOutput.setForeground(new java.awt.Color(255, 0, 0));
        lgErreurOutput.setText("      ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BoutonRetour)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Bouton_Close))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(147, 147, 147)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_mailInput1)
                            .addComponent(jLabel_mailInput)
                            .addComponent(jLabel_adresseInput)
                            .addComponent(jLabel_prenomInput)
                            .addComponent(jLabel_nomInput1)
                            .addComponent(jTextField_nomInput, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel_lgInput)
                                .addGap(18, 18, 18)
                                .addComponent(lgErreurOutput))
                            .addComponent(jTextField_telephoneInput, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_mailInput, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_adresseInput, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_lg_input1, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_prenomInput, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_mpInput)
                            .addComponent(jTextField_mp_input, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(203, 203, 203)
                        .addComponent(jButton_CreerAbonne)))
                .addContainerGap(163, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Bouton_Close)
                    .addComponent(BoutonRetour))
                .addGap(66, 66, 66)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_lgInput)
                    .addComponent(lgErreurOutput))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField_lg_input1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(jLabel_mpInput)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField_mp_input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel_nomInput1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField_nomInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_prenomInput)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField_prenomInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_adresseInput)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField_adresseInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_mailInput)
                .addGap(8, 8, 8)
                .addComponent(jTextField_mailInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_mailInput1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField_telephoneInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton_CreerAbonne)
                .addGap(46, 46, 46))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 524, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 563, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BoutonRetourMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BoutonRetourMouseClicked
        // TODO add your handling code here:
        
        this.dispose();
    }//GEN-LAST:event_BoutonRetourMouseClicked

    private void Bouton_CloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Bouton_CloseMouseClicked
        // TODO add your handling code here:
        
        System.exit(0);
    }//GEN-LAST:event_Bouton_CloseMouseClicked

    private void jButton_CreerAbonneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_CreerAbonneMouseClicked
        // TODO add your handling code here:
        String lg = jTextField_lg_input1.getText();
        String mp = jTextField_mp_input.getText();
        String nom = jTextField_nomInput.getText();
        String prenom = jTextField_prenomInput.getText();
        String adresse = jTextField_adresseInput.getText();
        String email = jTextField_mailInput.getText();
        String telephone = jTextField_telephoneInput.getText();
        Date dateDebutAbonnement = new Date();
        int confirmation;
        Abonne a;
        DialogConfirmationCreationAbonne dcca;
        
        
        a = ga.rechercheAbonne(lg);
        if ( a == null){
            
            dcca = new DialogConfirmationCreationAbonne(this, true,lg,mp, nom, prenom, adresse, email, telephone);
            dcca.setVisible(true);
            confirmation = dcca.getReturnStatus();
            
            if(confirmation == 1){
                ga.creerAbonne(lg,mp, nom, prenom, adresse, email, telephone, dateDebutAbonnement);
                GestionFinal.setGa(ga);
                this.dispose();
            }
            
            
        
        }else
        {
            lgErreurOutput.setText("Ce login n'est pas disponible");
        }
        
    
        
        
        
        
    }//GEN-LAST:event_jButton_CreerAbonneMouseClicked

   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FMenuCreationCompte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FMenuCreationCompte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FMenuCreationCompte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FMenuCreationCompte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new FMenuCreationCompte().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BoutonRetour;
    private javax.swing.JButton Bouton_Close;
    private javax.swing.JButton jButton_CreerAbonne;
    private javax.swing.JLabel jLabel_adresseInput;
    private javax.swing.JLabel jLabel_lgInput;
    private javax.swing.JLabel jLabel_mailInput;
    private javax.swing.JLabel jLabel_mailInput1;
    private javax.swing.JLabel jLabel_mpInput;
    private javax.swing.JLabel jLabel_nomInput1;
    private javax.swing.JLabel jLabel_prenomInput;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField_adresseInput;
    private javax.swing.JTextField jTextField_lg_input1;
    private javax.swing.JTextField jTextField_mailInput;
    private javax.swing.JTextField jTextField_mp_input;
    private javax.swing.JTextField jTextField_nomInput;
    private javax.swing.JTextField jTextField_prenomInput;
    private javax.swing.JTextField jTextField_telephoneInput;
    private javax.swing.JLabel lgErreurOutput;
    // End of variables declaration//GEN-END:variables
}
