/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Utilisation.Display;

import javax.swing.JFrame;
import Utilisation.*;
import Source.*;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JLabel;
/**
 *
 * @author GREGO
 */
public class GestionFinal extends javax.swing.JFrame {

    public static GestionAbonne getGa() {
        return ga;
    }

    public static void setGa(GestionAbonne ga) {
        GestionFinal.ga = ga;
    }

    public  static GestionTechnicien getGt() {
        return gt;
    }

    public static void setGt(GestionTechnicien gt) {
        GestionFinal.gt = gt;
    }

    public static GestionGestionnaire getGg() {
        return gg;
    }

    public static void setGg(GestionGestionnaire gg) {
        GestionFinal.gg = gg;
    }


    
    
    
    private static GestionAbonne ga;
    private static GestionTechnicien gt;
    private static GestionGestionnaire gg;
    
    private String profil_co = "Abonné";
    
    public GestionFinal() {
        initComponents();
        this.setLocationRelativeTo(null);
        
        ga = new GestionAbonne();
        gt = new GestionTechnicien();
        gg = new GestionGestionnaire();
        initialisation();
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        text_lg = new javax.swing.JTextField();
        lbl_mp = new javax.swing.JLabel();
        lbl_identifiant = new javax.swing.JLabel();
        lbl_titre = new javax.swing.JLabel();
        bouton_Quitter = new javax.swing.JButton();
        bouton_CreerCompte = new javax.swing.JButton();
        bouton_connexion = new javax.swing.JButton();
        lbl_information = new javax.swing.JLabel();
        text_mp = new javax.swing.JPasswordField();
        jRadioButtonMS = new javax.swing.JRadioButton();
        lblMessageOutput = new javax.swing.JLabel();

        jLabel2.setText("Identifiant");

        jTextField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField2.setText("Username");

        jButton2.setText("Quitter");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 98, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 74, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("tab1", jPanel2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        text_lg.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        lbl_mp.setText("Mot de passe");

        lbl_identifiant.setText("Identifiant");

        lbl_titre.setFont(new java.awt.Font("Arial Narrow", 0, 36)); // NOI18N
        lbl_titre.setText("SE CONNECTER");

        bouton_Quitter.setForeground(new java.awt.Color(102, 102, 102));
        bouton_Quitter.setText("Quitter");
        bouton_Quitter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bouton_QuitterMouseClicked(evt);
            }
        });

        bouton_CreerCompte.setForeground(new java.awt.Color(102, 102, 102));
        bouton_CreerCompte.setText("Créer un compte");
        bouton_CreerCompte.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bouton_CreerCompteMouseClicked(evt);
            }
        });

        bouton_connexion.setForeground(new java.awt.Color(102, 102, 102));
        bouton_connexion.setText("Connexion");
        bouton_connexion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bouton_connexionMouseClicked(evt);
            }
        });

        lbl_information.setText("Abonné");

        jRadioButtonMS.setText("Salarié");
        jRadioButtonMS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadioButtonMSMouseClicked(evt);
            }
        });

        lblMessageOutput.setFont(new java.awt.Font("DialogInput", 2, 14)); // NOI18N
        lblMessageOutput.setForeground(new java.awt.Color(255, 0, 51));
        lblMessageOutput.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bouton_Quitter)
                .addGap(16, 16, 16))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(380, 380, 380)
                .addComponent(bouton_connexion)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(303, 303, 303)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lbl_titre)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(lbl_identifiant)
                                .addComponent(lbl_mp)
                                .addComponent(text_lg)
                                .addComponent(text_mp, javax.swing.GroupLayout.DEFAULT_SIZE, 219, Short.MAX_VALUE))
                            .addComponent(lblMessageOutput, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_information)
                            .addComponent(bouton_CreerCompte)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(389, 389, 389)
                        .addComponent(jRadioButtonMS)))
                .addContainerGap(320, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bouton_Quitter)
                .addGap(82, 82, 82)
                .addComponent(lbl_titre)
                .addGap(47, 47, 47)
                .addComponent(lbl_identifiant)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(text_lg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbl_mp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(text_mp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jRadioButtonMS)
                .addGap(18, 18, 18)
                .addComponent(bouton_connexion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_information)
                    .addComponent(lblMessageOutput, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bouton_CreerCompte)
                .addGap(33, 33, 33))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bouton_QuitterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bouton_QuitterMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_bouton_QuitterMouseClicked

    private void bouton_CreerCompteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bouton_CreerCompteMouseClicked
        // TODO add your handling code here:
        
        FMenuCreationCompte mcc;
        mcc = new FMenuCreationCompte(ga);
        mcc.setVisible(true);
    }//GEN-LAST:event_bouton_CreerCompteMouseClicked

    private void bouton_connexionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bouton_connexionMouseClicked
        String lg = text_lg.getText();
        String mp = text_mp.getText();
        
        FMenuAbonne mm;
        FMenuGestionnaire mg;
        FMenuTechnicien mt;
        
        
     
     
     Abonne a= null;
     MembreSociete m = null;
     Technicien t = null;
     Gestionnaire g = null;
     
     
     
     
     
     if (profil_co.equals("Abonné"))
         {
          a = ga.rechercheAbonne(lg);
          
          if(a!=null)
          {
            do{
                if (a.getMp().equals(mp) && ga.validiteDateAbonne(a)) 
                {
                    
                    mm = new FMenuAbonne(a);
                    mm.setVisible(true);
                    
                } 
                else{
                    if(ga.validiteDateAbonne(a))
                    {
                        lblMessageOutput.setText("Erreur de mot de passe");
                    }
                    else{
                        lblMessageOutput.setText("La validité de votre compte a expiré");
                    }
                }
                    
            }while(!a.getMp().equals(mp));  
          }
          else{ lblMessageOutput.setText("Identifiant non trouvé");
          }
         }
         else
         {
             if(profil_co.equals("Salarié"))
             {
                 m = gg.rechercheMembreSociete(lg);
                 if(m!=null)
                {
                    do{
                        if (m.getMp().equals(mp)) 
                        {
                            if (m instanceof Gestionnaire)
                            {
                                g= (Gestionnaire)m;
                                mg = new FMenuGestionnaire(g);
                                mg.setVisible(true);
                            }
                            else
                            {
                                t =(Technicien)m;
                                mt = new FMenuTechnicien(t);
                                mt.setVisible(true);
                            }
                        } 
                        else
                        {
                            lblMessageOutput.setText("Mauvais mot de passe");
                        }
                    }while(!m.getMp().equals(mp));
                }
                 else{
                        lblMessageOutput.setText("Salarié non reconnus");    
                            }
             }
         }
    
    
    
        
        
        
    }//GEN-LAST:event_bouton_connexionMouseClicked

    private void jRadioButtonMSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButtonMSMouseClicked
        // TODO add your handling code here:
        if (profil_co.equalsIgnoreCase("Abonné")){
            profil_co = "Salarié";
        }
        else{
            profil_co = "Abonné";
        }
    }//GEN-LAST:event_jRadioButtonMSMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestionFinal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestionFinal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestionFinal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestionFinal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GestionFinal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bouton_CreerCompte;
    private javax.swing.JButton bouton_Quitter;
    private javax.swing.JButton bouton_connexion;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRadioButtonMS;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JLabel lblMessageOutput;
    private javax.swing.JLabel lbl_identifiant;
    private javax.swing.JLabel lbl_information;
    private javax.swing.JLabel lbl_mp;
    private javax.swing.JLabel lbl_titre;
    private javax.swing.JTextField text_lg;
    private javax.swing.JPasswordField text_mp;
    // End of variables declaration//GEN-END:variables

    
    public void  initialisation(){
    
    Gestionnaire g;
    Technicien t;
    int n =2;
    String x;
    ArrayList<Borne>initialisationB= new ArrayList();
    Borne b;
    
    TypeReparation tr;
    ArrayList<Velo>initialisationV= new ArrayList();
    Velo v;
    EtatVelo e;
    StatutVelo s;
    int i = 0;
    
    for (i=0; i< n; i++){
        x =i+ "Luix";
        g = new Gestionnaire(x, x, "Jean "+x, "Roger "+x, new Date());
        gg.getListeMembreSociete().add(g);
        System.out.println("Profil Gestionnaire : " + g.getInfos() + "Id & mp: " + x + "\n");
    }
    System.out.println("---------------- Gestionnaires initialisés ---------------");
    i = 0;
    for (i=0; i< n; i++){
        x =i+ "Lui";
        t = new Technicien(x, x, "Michel "+x, "Patrick "+x, new Date());
        gg.getListeMembreSociete().add(t);
        System.out.println("Profil Technicien : " + t.getInfos()+ "Id & mp: " + x + "\n");
    }
    
    
    System.out.println("---------------- Techniciens initialisés ---------------");
    
    n = 4;
    i = 0;
    
    for (i=0; i< n-1; i++){
        x = "3" + i+ "rue Enrouée";
        i++;
        b = new Borne(x, i);
        initialisationB.add(b);
        System.out.println("Borne : " + b.getInfo() + "\n");
        i--;
    }
    gt.setListeBorne(initialisationB);
    System.out.println("---------------- Bornes initialisés ---------------");
   
    i = 0;
    
    for (i=0; i< n; i++){
        x = "Réparation de la visse n°"+ i;
        
        tr = new TypeReparation(x);
        gt.getListeTypeReparation().add(tr);
        System.out.println("Type de réparation : " + tr.getId() + "\n");
        
    }
    
    System.out.println("---------------- Types de réparations initialisés ---------------");
    
    
    e = new EtatVelo("Mauvais");
    gt.getListeEtatVelo().add(e);
    System.out.println("Etat:" + e.getEtat() + " ID:"+ e.getId());
    e = new EtatVelo("Moyen");
    gt.getListeEtatVelo().add(e);
    System.out.println("Etat:" + e.getEtat() + " ID:"+ e.getId());
    e = new EtatVelo("Bon");
    gt.getListeEtatVelo().add(e);
    System.out.println("Etat:" + e.getEtat() + " ID:"+ e.getId());
    System.out.println("---------------- Etats de vélo initialisés ---------------");
    
    s = new StatutVelo("En cours de location");
    gt.getListeStatutVelo().add(s);
    System.out.println("Statut:" + s.getStatut() + " ID:"+ s.getId());
    s = new StatutVelo("En cours de réparation");
    gt.getListeStatutVelo().add(s);
    System.out.println("Statut:" + s.getStatut() + " ID:"+ s.getId());
    s = new StatutVelo("Détruit");
    gt.getListeStatutVelo().add(s);
    System.out.println("Statut:" + s.getStatut() + " ID:"+ s.getId());
    s = new StatutVelo("Disponible");
    gt.getListeStatutVelo().add(s);
    System.out.println("Statut:" + s.getStatut() + " ID:"+ s.getId());
    System.out.println("---------------- Statuts de vélo initialisés ---------------");
    
    
    n = (gt.getListeEtatVelo().size()-1)*(gt.getListeStatutVelo().size()-1)+1;
    int u = 0;
    i = 0;
    
    for (i=0; u*i< n; i++){
        v = new Velo(new Date(),gt.getListeEtatVelo().get(i), gt.getListeStatutVelo().get(u));
        initialisationV.add(v);
        System.out.println("Velo : " + v.getInfo() + "\n");
        
        if ((i*u<n-1)&&(i == gt.getListeEtatVelo().size()-1)){u++;i=-1;}
    }
    gt.setListeVelo(initialisationV);
    System.out.println("---------------- Vélos initialisés ---------------");
    
    
}
}
