/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Utilisation.Display;

/**
 *
 * @author GREGO
 */
public class MenuCreationCompte extends javax.swing.JPanel {

    /**
     * Creates new form CreationCompte
     */
    public MenuCreationCompte() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Bouton_Close = new javax.swing.JButton();
        jTextField_mp_input = new javax.swing.JTextField();
        jTextField_lg_input1 = new javax.swing.JTextField();
        jTextField_adresseInput = new javax.swing.JTextField();
        jTextField_prenomInput = new javax.swing.JTextField();
        jTextField_telephoneInput = new javax.swing.JTextField();
        jTextField_nomInput = new javax.swing.JTextField();
        jTextField_mailInput = new javax.swing.JTextField();
        jLabel_lgInput = new javax.swing.JLabel();
        jLabel_mpInput = new javax.swing.JLabel();
        jLabel_prenomInput = new javax.swing.JLabel();
        jLabel_nomInput1 = new javax.swing.JLabel();
        jLabel_adresseInput = new javax.swing.JLabel();
        jLabel_mailInput = new javax.swing.JLabel();
        jLabel_mailInput1 = new javax.swing.JLabel();
        jButton_CreerAbonne = new javax.swing.JButton();
        BoutonRetour = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setForeground(new java.awt.Color(255, 255, 255));

        Bouton_Close.setText("Fermer");

        jLabel_lgInput.setText("Login");

        jLabel_mpInput.setText("Mot de passe");

        jLabel_prenomInput.setText("Prénom");

        jLabel_nomInput1.setText("Nom");

        jLabel_adresseInput.setText("Adresse");

        jLabel_mailInput.setText("Courriel");

        jLabel_mailInput1.setText("Téléphone");

        jButton_CreerAbonne.setText("S'inscrire");

        BoutonRetour.setText("Retour");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BoutonRetour)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Bouton_Close))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(147, 147, 147)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_mailInput1)
                            .addComponent(jLabel_mailInput)
                            .addComponent(jLabel_adresseInput)
                            .addComponent(jLabel_prenomInput)
                            .addComponent(jLabel_nomInput1)
                            .addComponent(jTextField_nomInput, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_lgInput)
                            .addComponent(jTextField_telephoneInput, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_mailInput, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_adresseInput, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_lg_input1, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_prenomInput, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_mpInput)
                            .addComponent(jTextField_mp_input, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(203, 203, 203)
                        .addComponent(jButton_CreerAbonne)))
                .addContainerGap(163, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Bouton_Close)
                    .addComponent(BoutonRetour))
                .addGap(66, 66, 66)
                .addComponent(jLabel_lgInput)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField_lg_input1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(jLabel_mpInput)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField_mp_input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel_nomInput1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField_nomInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_prenomInput)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField_prenomInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_adresseInput)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField_adresseInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_mailInput)
                .addGap(8, 8, 8)
                .addComponent(jTextField_mailInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_mailInput1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField_telephoneInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton_CreerAbonne)
                .addGap(46, 46, 46))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BoutonRetour;
    private javax.swing.JButton Bouton_Close;
    private javax.swing.JButton jButton_CreerAbonne;
    private javax.swing.JLabel jLabel_adresseInput;
    private javax.swing.JLabel jLabel_lgInput;
    private javax.swing.JLabel jLabel_mailInput;
    private javax.swing.JLabel jLabel_mailInput1;
    private javax.swing.JLabel jLabel_mpInput;
    private javax.swing.JLabel jLabel_nomInput1;
    private javax.swing.JLabel jLabel_prenomInput;
    private javax.swing.JTextField jTextField_adresseInput;
    private javax.swing.JTextField jTextField_lg_input1;
    private javax.swing.JTextField jTextField_mailInput;
    private javax.swing.JTextField jTextField_mp_input;
    private javax.swing.JTextField jTextField_nomInput;
    private javax.swing.JTextField jTextField_prenomInput;
    private javax.swing.JTextField jTextField_telephoneInput;
    // End of variables declaration//GEN-END:variables
}
