/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Utilisation.Display;

/**
 *
 * @author GREGO
 */
public class MenuAbonne extends javax.swing.JPanel {

    /**
     * Creates new form MenuAbonne
     */
    public MenuAbonne(String test) {
        
        initComponents();
        lblMessageOutput.setText(test);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BoutonFermer = new javax.swing.JButton();
        BoutonRetour = new javax.swing.JButton();
        BoutonCreerLocation = new javax.swing.JButton();
        BoutonModifierLocation = new javax.swing.JButton();
        BoutonModifierCompte = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        lblMessage = new javax.swing.JLabel();
        lblMessageOutput = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        BoutonFermer.setText("Fermer");

        BoutonRetour.setText("Retour");

        BoutonCreerLocation.setText("Créer une location");

        BoutonModifierLocation.setText("Modifier une location");

        BoutonModifierCompte.setText("Modifier mon compte");

        jButton1.setText("Supprimer mon compte");

        lblMessage.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        lblMessage.setText("Message");

        lblMessageOutput.setText("Message");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BoutonRetour)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BoutonFermer)))
                .addGap(15, 15, 15))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(349, 349, 349)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BoutonCreerLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BoutonModifierLocation)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(307, 307, 307)
                        .addComponent(BoutonModifierCompte, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(lblMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(83, Short.MAX_VALUE)
                .addComponent(lblMessageOutput, javax.swing.GroupLayout.PREFERRED_SIZE, 664, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(99, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BoutonFermer)
                    .addComponent(BoutonRetour))
                .addGap(27, 27, 27)
                .addComponent(lblMessage)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblMessageOutput, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(BoutonModifierCompte)
                .addGap(18, 18, 18)
                .addComponent(BoutonModifierLocation)
                .addGap(18, 18, 18)
                .addComponent(BoutonCreerLocation)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 161, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BoutonCreerLocation;
    private javax.swing.JButton BoutonFermer;
    private javax.swing.JButton BoutonModifierCompte;
    private javax.swing.JButton BoutonModifierLocation;
    private javax.swing.JButton BoutonRetour;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel lblMessage;
    private javax.swing.JLabel lblMessageOutput;
    // End of variables declaration//GEN-END:variables
}
